-- 0066_web2_platforms_more.sql
-- More real web 2.0 publishing platforms sourced (non-blocking: open self-serve
-- signup or anonymous publish; no invite/waitlist/OAuth-app-approval; brand-safe).
-- automation_ready stays false (no Web2Publisher class yet) - these grow the honest
-- strategy inventory, exactly like 0063. Idempotent via unique(name).
insert into public.web2_platforms
  (name, homepage_url, signup_url, publish_url_or_method, auth_type, authority_tier, market, automation_ready, notes)
values
  ('HackMD','https://hackmd.io','https://hackmd.io/','api: POST /v1/notes at api.hackmd.io with Bearer token (token self-issued in Settings > API); set note permission to public so the note URL is indexable','api','medium','global',false,'Collaborative markdown editor; notes can be set public/published and are crawlable. Self-serve token, no approval. Signup via OAuth logins (GitHub/Google) from the homepage.'),
  ('GitHub Gist','https://gist.github.com','https://github.com/signup','api: POST https://api.github.com/gists with a PAT (Bearer); set public:true to create an indexable gist page','api','high','global',false,'Extremely high DA and self-serve. Caveat: gist/code links are typically nofollow — best for reference/citation diversity and brand mentions rather than raw link equity.'),
  ('GitLab Snippets','https://gitlab.com','https://gitlab.com/users/sign_up','api: POST https://gitlab.com/api/v4/snippets with `PRIVATE-TOKEN` PAT header; visibility=public produces a public indexable snippet','api','high','global',false,'High-DA, fully self-serve PAT (no app approval). Public snippets are indexable; outbound links generally nofollow. Distinct API/domain from GitHub.'),
  ('rentry.co','https://rentry.co','https://rentry.co/','anonymous: POST https://rentry.co/api/new with a CSRF token (fetched from a cookie) + markdown body → returns the public URL and an edit_code; content stays permanent','anonymous','medium','global',false,'Anonymous markdown pages, no account, permanent (no forced expiry). Unofficial-but-stable /api/new endpoint (needs the CSRF cookie handshake). Anonymous creation is IP rate-limited (~10/min).'),
  ('JustPaste.it','https://justpaste.it','https://justpaste.it/','automation: paste rich HTML/text + images into the web editor at justpaste.it and publish anonymously; no documented public write API, so drive the editor via browser automation','automation','medium','global',false,'Renders full anonymous articles with images and HTML formatting — good for content-rich placements. No official/public write API found, so automation is browser-driven. Anonymous publish, no account required.'),
  ('paste.ee','https://paste.ee','https://paste.ee/register','api: POST https://api.paste.ee/v1/pastes with `X-Auth-Token` header (key self-issued in the account dashboard) + sections[].contents','api','low','global',false,'Self-serve API token, no approval. Low authority, code/text oriented. Clean JSON API returning a public paste URL.'),
  ('dpaste.org','https://dpaste.org','https://dpaste.org/','anonymous: POST https://dpaste.org/api/ with `content` (and format=url to get a plain URL back); no key or account needed','anonymous','low','global',false,'Simplest possible anonymous POST — no key. Caveat: pastes can expire (pick the longest retention option), so weaker for permanent backlinks. Low authority.'),
  ('Pastebin.com','https://pastebin.com','https://pastebin.com/signup','api: POST https://pastebin.com/api/api_post.php with api_dev_key + api_option=paste + api_paste_code (dev key auto-issued to any logged-in member)','api','medium','global',false,'Classic high-traffic paste host. Self-serve api_dev_key from your account. Code/text oriented; outbound links usually nofollow. Set api_paste_expire_date=N (never) and api_paste_private=0 (public) for a lasting indexable paste.'),
  ('Bear Blog','https://bearblog.dev','https://bearblog.dev/register/','automation: sign up for a free <name>.bearblog.dev, write markdown in the dashboard editor and hit publish (no public write API)','automation','low','global',false,'Free, super-fast, no-nonsense blog on a bearblog.dev subdomain; followed links, clean pages. No public API — must drive the web editor. Custom domain/media need the $5/mo upgrade but publishing is free.'),
  ('Mastodon (mastodon.social)','https://mastodon.social','https://mastodon.social/auth/sign_up','api: POST /api/v1/statuses with a self-issued Bearer token (Settings > Development > New application), or full OAuth via POST /api/v1/apps','api','high','global',false,'Fediverse flagship, high-DA domain. Open email signup (occasionally flips to admin-approval during spam waves). A self-issued access token skips the OAuth dance. Outbound links are rel=nofollow/UGC - value is indexation + referral + entity/brand signal, not raw link equity.'),
  ('Mastodon (mas.to)','https://mas.to','https://mas.to/auth/sign_up','api: POST /api/v1/statuses with a self-issued Bearer token (same Mastodon REST API as mastodon.social)','api','medium','global',false,'Large general-purpose Mastodon instance with reliably OPEN self-serve registration (unlike some flagships that gate during spam waves). Distinct referring domain - good for fediverse link diversity. Links nofollow.'),
  ('Misskey (misskey.io)','https://misskey.io','https://misskey.io','api: POST /api/notes/create with an access token minted in Settings > API','api','medium','jp',false,'Largest Misskey (distinct fediverse software, not a Mastodon fork) server, Japan-centric, open self-serve signup via on-page modal. Clean token-based API. Good for JP-market entity signals; links nofollow.'),
  ('Pixelfed (pixelfed.social)','https://pixelfed.social','https://pixelfed.social/register','oauth: register an app for an OAuth token, then POST /api/v1/statuses (Mastodon-compatible) with an image; link goes in the caption/bio','oauth','medium','global',false,'Image-first fediverse (Instagram-like). Registration open (occasionally waved closed for spam). Requires an image per post; caption links are nofollow. Best for image-led properties rather than pure link drops.'),
  ('Lemmy (lemmy.world)','https://lemmy.world','https://lemmy.world/signup','api: POST /api/v3/user/login for a JWT, then POST /api/v3/post (name + url + body) to a community','api','medium','global',false,'Largest Lemmy (Reddit-like fediverse) instance, open self-serve signup. Link posts must fit a relevant community and survive moderation/spam filters. Outbound links typically nofollow; value is topical referral + indexation.'),
  ('Bluesky','https://bsky.app','https://bsky.app','api: create an App Password at bsky.app/settings/app-passwords, com.atproto.server.createSession, then com.atproto.repo.createRecord (app.bsky.feed.post)','api','high','global',false,'Fully open - no dev portal, no review, no invite (44M+ users as of 2026). App Passwords are instant self-serve; OAuth is the newer path. The best-automatable major microblog here. Posts crawlable via bsky.app; supports link facets and threaded longer content.'),
  ('WhiteWind (Bluesky/ATProto long-form)','https://whtwnd.com','https://whtwnd.com','api: sign in with your Bluesky (ATProto) account, then write a com.whtwnd.blog.entry record to your PDS via XRPC; it renders as a public HTML article at whtwnd.com','api','medium','global',false,'ATProto Markdown blog service - free with any Bluesky account, no extra signup or personal info. Articles render as public, crawlable HTML pages, giving a real long-form backlink surface on ATProto (vs. ephemeral posts). Directly matches the ''Bluesky long-form'' target.'),
  ('Nostr long-form (YakiHonne / Habla.news)','https://yakihonne.com','https://yakihonne.com','api: generate a Nostr keypair (or use a NIP-07 signer), sign and publish a kind:30023 long-form event to relays; web frontends render it as a crawlable HTML article at yakihonne.com / habla.news','api','low','global',false,'Nostr NIP-23 long-form. No gatekeeper at all - create a key and publish. YakiHonne and Habla.news render public, crawlable article pages. Emerging/low authority; value is protocol diversification + a censorship-resistant mirror of content.'),
  ('Listed.to (Standard Notes)','https://listed.to','https://listed.to','automation: create a free Listed blog and publish from the Standard Notes app (add the note to your ''Listed'' publication / use the publish action); no public write API','automation','low','global',false,'Minimal public-journal blogging tied to Standard Notes; free self-serve. Produces crawlable pages with email subscribe. Publishing is app-driven (no token API) -> browser/app automation. Low authority but a clean, distinct property.'),
  ('diaspora* (diasp.org)','https://diasp.org','https://diasp.org/users/sign_up','automation: post via the pod''s web composer; no official write API - the unofficial ''diaspy'' Python client logs in with a session and posts','automation','low','global',false,'diaspora* pod (network still active, v0.9.1.x in 2026). Open self-serve signup on diasp.org, though individual pods can close registration - if diasp.org is closed, pick another open pod (podupti.me). Federated; no first-party API -> session-based browser automation. Low authority.'),
  ('Netlify','https://www.netlify.com','https://app.netlify.com/signup','Deploy via Netlify API/CLI (netlify deploy) with a personal access token; free site served at *.netlify.app.','api','medium','global',false,'Free *.netlify.app subdomain. PAT self-serve. Static hosting; fully automatable. Medium DA.'),
  ('Neocities','https://neocities.org','https://neocities.org','API key from dashboard; POST https://neocities.org/api/upload to push HTML files to username.neocities.org.','api','medium','global',false,'Free static host, self-serve signup and API key. Fully automatable. Medium DA.'),
  ('Webflow','https://webflow.com','https://webflow.com/signup','Data API v2 (Bearer site token) to create/publish CMS items; free Starter site served at *.webflow.io.','api','medium','global',false,'Free Starter gives *.webflow.io staging subdomain (Webflow branding, no custom domain, 2 pages/50 CMS items). Token self-serve in site settings; some API/publish limits on free tier. Medium DA.'),
  ('Wikidot','https://www.wikidot.com','https://www.wikidot.com/default--flow/login__CreateAccountScreen','Create a free wiki, then add/edit pages in the wiki editor. (Legacy XML-RPC API exists but is limited/unmaintained.)','automation','low','global',false,'Confirmed live 2026 but on ''life support'' — development stalled, no custom support. Free yourwiki.wikidot.com, email-confirm signup. Low DA.')
on conflict (name) do nothing;
