-- 0067_directories_more2.sql
-- More citation directories sourced (non-blocking: open signup / public add-business
-- form; no paid-only/invite/dead). Idempotent via unique(name, market).
insert into public.directories (name, url, market, tier, submit_method, automation_note) values
  ('Google Business Profile','https://business.google.com/','GLOBAL','manual_only','playwright','signup:https://www.google.com/business/ | Foundational citation. Free self-serve signup, no paid wall, but requires a Google account plus phone/postcard/video verification and there is no clean single add-a-business form, so automation is account/verify-heavy (manual).'),
  ('Superpages','https://www.superpages.com/','US','manual_only','playwright','signup:https://www.superpages.com/ | Free basic listing (limited features) via Claim/Update flow; account required, paid upgrades upsold. Thryv brand, same network as YP/DexKnows.'),
  ('Cylex US','https://www.cylex.us.com/','US','captcha_assisted','playwright','signup:https://www.cylex.us.com/add-company.html | Free listing: register a user account, then ''Register business'' form (NAP, keywords, description). Captcha-guarded; premium upsell exists but basic is free.'),
  ('n49','https://www.n49.com/','GLOBAL','captcha_assisted','playwright','signup:https://www.n49.com/add-business/ | Free ''Free Forever'' basic listing via add-business form; optional paid verified upgrade ($10/mo). International with strong US/CA coverage. Captcha likely.'),
  ('iBegin','https://www.ibegin.com/','GLOBAL','manual_only','playwright','signup:https://www.ibegin.com/directory/ | Free ''Submit a Business'' listing: create an account and complete phone verification. Phone-verify makes it manual. International (US/CA/UK/NZ).'),
  ('Fyple UK','https://www.fyple.co.uk/','UK','manual_only','playwright','signup:https://www.fyple.co.uk/register/ | Free international directory, UK domain. Register account + email confirm, then add company details. Account-gated but fully free.'),
  ('Bizify','https://www.bizify.co.uk/','UK','manual_only','playwright','signup:https://www.bizify.co.uk/register | Free listing for any UK-registered business. Must sign in/register then follow on-screen steps. Priority/premium upgrade optional. Confirm exact register URL from homepage sign-up link.'),
  ('Trustpilot','https://www.trustpilot.com/','GLOBAL','manual_only','playwright','signup:https://business.trustpilot.com/signup | Free plan lets you claim/create a company profile page (name, domain, logo) - a strong citation + review property. It''s primarily a reviews platform; account required, no credit card for free tier.'),
  ('Yelp for Business (Yelp Canada)','https://www.yelp.ca/','CA','manual_only','playwright','signup:https://business.yelp.com/ | Live. biz.yelp.com 302-redirects to business.yelp.com (confirmed). Free to add/claim a business; serves Canada via yelp.ca. Requires account creation and email/phone confirmation, so not a clean anonymous form.'),
  ('Yalwa Canada','https://www.yalwa.ca/','CA','captcha_assisted','playwright','signup:https://www.yalwa.ca/ | Live (server responds, 403 to bot UA = WAF). Free ''advertise/post your business'' listing. Requires email confirmation and has a captcha. Use the ''Add your business / Advertise'' link from the homepage.'),
  ('iBegin','https://www.ibegin.com/','CA','captcha_assisted','playwright','signup:https://www.ibegin.com/ | Live North American (US + Canada) directory with an open ''Add a Business'' listing form (free). Returns 403 to bot user-agents (Cloudflare/anti-bot), so automation will hit a challenge - treat as captcha/anti-bot assisted.'),
  ('Kompass Canada','https://ca.kompass.com/','CA','manual_only','playwright','signup:https://ca.kompass.com/ | Live B2B directory, Canadian subdomain. Free basic company registration (paid tiers exist for premium). Requires creating an account to add a company - manual/assisted. Returns 403 to bots (WAF).'),
  ('Cybo','https://www.cybo.com/','GLOBAL','captcha_assisted','playwright','signup:https://www.cybo.com/add-company/ | Live global business directory with Canada coverage. Free ''Add company'' form at /add-company/. Server returns 403 to bot user-agents (WAF), and the form carries a captcha - budget for anti-bot handling.'),
  ('EnrollBusiness','https://www.enrollbusiness.com/','GLOBAL','captcha_assisted','playwright','signup:https://www.enrollbusiness.com/ | Live global directory with per-country sections including Canada; free ''List Your Business'' listing. Returns 403 to bot user-agents (WAF) and uses a captcha on the submit form - assisted automation.'),
  ('Storeboard','https://www.storeboard.com/','GLOBAL','manual_only','playwright','signup:https://www.storeboard.com/ | Live business directory / business social network with free listings (Canada supported). Requires free account signup before adding a business - manual/assisted. Returns 403 to bot UAs (WAF).'),
  ('Word of Mouth','https://www.wordofmouth.com.au/','AU','manual_only','playwright','signup:https://www.wordofmouth.com.au/users/new_with_business | Live review-driven AU directory. Verified free ''Register your business'' flow at /users/new_with_business. Freemium (paid ''WOMO Pro'' upsell). Requires account registration to submit.'),
  ('PureLocal','https://www.purelocal.com.au/','AU','captcha_assisted','playwright','signup:https://www.purelocal.com.au/ | Live AU business directory, free listing. Branded around ''verified listings'' so expect a verification/captcha step on the Add Your Business form. Add link is on the homepage rather than a fixed deep URL.'),
  ('Pink Pages','https://www.pinkpages.com.au/','AU','captcha_assisted','playwright','signup:https://www.pinkpages.com.au/ | Live AU business directory, free listings. Add-your-business form accessible from the site; likely reCAPTCHA-guarded and/or email verification.'),
  ('Local Business Guide','https://www.localbusinessguide.com.au/','AU','bot_fillable','playwright','signup:https://www.localbusinessguide.com.au/ | Free AU directory that appears in current 2026 citation lists. Straightforward public add-business form; low friction. Verify captcha presence at submit time.'),
  ('List Local Australia','https://listlocal.com.au/','AU','captcha_assisted','playwright','signup:https://listlocal.com.au/add-business | Live free AU online directory. Verified public add-business URL (listlocal.com.au/add-business). Expect a captcha/email step; otherwise a simple listing form.'),
  ('Opendi Australia','https://www.opendi.com.au/','AU','captcha_assisted','playwright','signup:https://www.opendi.com.au/ | AU domain of the Opendi global directory network. Free ''add your company'' listing; add link on homepage. Expect captcha/email verification.'),
  ('Australian Planet','https://www.australianplanet.com/','AU','bot_fillable','playwright','signup:https://www.australianplanet.com/ | Long-running free AU web/business directory. Simple public URL/business submission form, low friction. Confirm captcha at submit; otherwise clean fillable.'),
  ('Cylex','https://www.cylex.com/','GLOBAL','captcha_assisted','playwright','signup:https://www.cylex.com/add-company.html | Large network of country-specific business directories (cylex.us.com, .co.uk, .de, etc.). Free ''Add company'' form per country; captcha + email confirmation. Exact add-path varies by country domain.'),
  ('Opendi','https://www.opendi.us/','GLOBAL','captcha_assisted','playwright','signup:https://www.opendi.us/ | Network of country directories (opendi.us, .co.uk, .de, etc.). Free add-company form per locale, captcha-guarded. Add-path lives under each country domain.'),
  ('Tuugo','https://www.tuugo.us/','GLOBAL','captcha_assisted','playwright','signup:https://www.tuugo.us/RegisterFirms | Worldwide directory network with per-country domains (tuugo.us, .co.uk, tuugo.info, etc.). Free ''register firm'' form; captcha present. Reliable free citation.'),
  ('Yalwa','https://www.yalwa.com/','GLOBAL','captcha_assisted','playwright','signup:https://www.yalwa.com/ | Global classifieds/business directory with many country domains (yalwa.com, .co.uk, .ca, etc.). Free add-business flow, captcha + email verify. Choose the correct country domain for the listing.'),
  ('Fyple','https://www.fyple.com/','GLOBAL','captcha_assisted','playwright','signup:https://www.fyple.com/add/ | International directory network (fyple.com, fyple.biz, fyple.co.uk, etc.). Free public add-company form; captcha-guarded. Straightforward citation source.'),
  ('Europages','https://www.europages.com/','GLOBAL','manual_only','playwright','signup:https://www.europages.com/en/register | Large European/international B2B directory. General-business (not single-vertical). Free basic listing exists but requires creating a company account and completing a multi-step profile; upsell to paid plans is heavy but a free listing is available.'),
  ('Kompass','https://www.kompass.com/','GLOBAL','manual_only','playwright','signup:https://www.kompass.com/en/register | Global B2B business directory. Free basic company registration available, but account-gated and steered toward paid EasyBusiness upgrades. Legitimate general citation; automation must handle the multi-step registration.')
on conflict (name, market) do nothing;
