"""P0-1 REGRESSION GUARD: the content writer must state its OWN system contract.

Prevented defect (found 2026-08-24, present since the module shipped): NOTHING in the
content path passed ``system=`` to the writer. ``AnthropicSummarizer.summarize`` does
``system or _COMPACTION_SYSTEM_PROMPT``, so every article section ever drafted was
generated by a model that had been told:

    "You maintain a bounded, factual living summary of one entity's activity ...
     produce an updated summary that drops contradicted or expired facts."

That is the Part-6B context-COMPACTION contract. Claude was instructed to act as a
summarisation service and then asked to write marketing copy. The gated wrapper in
``workers/tasks/content.py`` did not even ACCEPT a ``system`` parameter, so the pure
generator had no way to pass one even if it had tried.

Why this file exists rather than a comment: the bug was INVISIBLE to the whole existing
suite. Every content test injects a fake writer, and a fake that ignores ``system``
produces byte-identical output whether the contract is right, wrong, or absent. A test
that only asserts on returned text can never catch this class of defect - so these
tests assert on what the writer was ASKED, not on what it returned.
"""

from __future__ import annotations

import ast
import pathlib

import pytest

from app.services.content_generator import CONTENT_SYSTEM_PROMPT
from integrations.llm import _COMPACTION_SYSTEM_PROMPT
from tests.test_content_generator import (  # reuse the established builders
    FakeWriter,
    _brief,
    _context,
    _source_pack,
)

_BACKEND = pathlib.Path(__file__).resolve().parents[1]

# Every module in the content path that is allowed to reach the writer at all.
_CONTENT_WRITER_MODULES: tuple[str, ...] = (
    "app/services/content_generator.py",
    "app/services/content_guard.py",
)


# --------------------------------------------------------------------------- #
# 1 - the contract is distinct from the compaction default
# --------------------------------------------------------------------------- #
def test_content_system_prompt_is_not_the_compaction_prompt() -> None:
    """The whole point of P0-1. If these ever converge, the fix has been undone."""
    assert CONTENT_SYSTEM_PROMPT != _COMPACTION_SYSTEM_PROMPT
    # The compaction prompt's tell: it asks for a SUMMARY of an entity's activity.
    assert "living summary" not in CONTENT_SYSTEM_PROMPT
    assert "updated summary" not in CONTENT_SYSTEM_PROMPT


def test_content_system_prompt_states_the_load_bearing_rules() -> None:
    """The contract must carry the rules the QA scorecard later grades against, so a
    draft is not marked down for a rule it was never told."""
    lowered = CONTENT_SYSTEM_PROMPT.lower()
    assert "never invent" in lowered            # fact_grounding
    assert "em dash" in lowered                  # the content_guard dash guarantee
    assert "experience" in lowered               # eeat_experience / doctrine Law 16


# --------------------------------------------------------------------------- #
# 2 - the generator actually passes it, on EVERY call
# --------------------------------------------------------------------------- #
def test_generate_passes_the_content_contract_on_every_writer_call() -> None:
    writer = FakeWriter()
    generate_ = __import__(
        "app.services.content_generator", fromlist=["generate"]
    ).generate
    generate_(_brief(), _source_pack(), _context(), page_type="blog", writer=writer)

    assert writer.calls > 0, "fixture no longer exercises the writer"
    recorded = getattr(writer, "systems", [])
    assert len(recorded) == writer.calls, "a writer call slipped through unrecorded"
    assert all(s == CONTENT_SYSTEM_PROMPT for s in recorded), (
        "at least one section was drafted WITHOUT the content contract, which means it "
        f"fell through to the compaction prompt. Got: {set(recorded)!r}"
    )


# --------------------------------------------------------------------------- #
# 3 - the gated wrapper FORWARDS it (the link that was structurally missing)
# --------------------------------------------------------------------------- #
def test_gated_writer_forwards_system_to_the_inner_writer() -> None:
    """``_ContentGatedWriter`` is the only door to the provider. If it drops ``system``
    the generator's contract dies silently at the last hop - which is exactly the shape
    of the original defect."""
    from workers.tasks.content import _ContentGatedWriter

    seen: dict[str, object] = {}

    class _Inner:
        def summarize(self, prompt, *, model, max_tokens, system=None, cache=None):
            seen["system"] = system
            seen["cache"] = cache
            from integrations.llm import LLMResult

            return LLMResult(text="ok", input_tokens=1, output_tokens=1)

    class _AllowGate:
        def evaluate(self, ctx):
            return type("D", (), {"allowed": True, "outcome": "call"})()

        def commit(self, ctx, actual):
            return None

    from app.config import Settings

    gated = _ContentGatedWriter(
        _Inner(), _AllowGate(), settings=Settings(), client_id=None, job_id="CJ-TEST"
    )
    gated.summarize(
        "hello", model="m", max_tokens=10, system=CONTENT_SYSTEM_PROMPT, cache=[True]
    )
    assert seen["system"] == CONTENT_SYSTEM_PROMPT
    # P1B widened the seam to carry per-block cache flags. The wrapper must forward
    # BOTH, or the doctrine blocks arrive uncached and cost 10x to read.
    assert seen["cache"] == [True]


# --------------------------------------------------------------------------- #
# 4 - STATIC guard: no future writer call may omit system=
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("relpath", _CONTENT_WRITER_MODULES)
def test_every_writer_call_in_the_content_path_passes_system(relpath: str) -> None:
    """Runtime tests only cover the paths a fixture happens to walk. This one reads the
    source, so a NEW ``writer.summarize(...)`` added tomorrow cannot quietly reintroduce
    the compaction-prompt fallback."""
    path = _BACKEND / relpath
    tree = ast.parse(path.read_text(), filename=str(path))

    offenders: list[int] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        func = node.func
        if not (isinstance(func, ast.Attribute) and func.attr == "summarize"):
            continue
        # only calls on a `writer`-ish receiver
        recv = func.value
        recv_name = recv.id if isinstance(recv, ast.Name) else getattr(recv, "attr", "")
        if "writer" not in recv_name.lower():
            continue
        if not any(kw.arg == "system" for kw in node.keywords):
            offenders.append(node.lineno)

    assert not offenders, (
        f"{relpath}: writer.summarize() without system= at line(s) {offenders}. "
        "Without it the call falls back to llm._COMPACTION_SYSTEM_PROMPT and the "
        "model is told it is a summariser. Pass system=CONTENT_SYSTEM_PROMPT."
    )
