#!/usr/bin/env python3
"""information_gain_scorer.py - Score a draft's net-new value vs a consensus baseline.

Offline, stdlib-only (argparse, re, os, sys, difflib). No network calls. This
script never calls a model or an API: the "consensus" baseline (the bland,
generic answer for the target query) is generated by the caller and passed in
as a file. This tool only measures the residual.

Operationalizes Law 15 (information gain over coverage). Google's information-
gain patent rewards what a page ADDS beyond the SERP consensus, not how
completely it matches it. So the test is: generate the bland consensus answer,
diff the draft against it, and measure the residual - the material present in
the draft but absent from the consensus. A thin residual means the page is a
rehash and PARTIAL at best.

What it computes
----------------
- Residual ratio: the proportion of the draft's word sequence NOT aligned to
  the consensus, via difflib longest-matching-block alignment. Higher = more
  net-new material. This is the headline information-gain number.
- Net-new inventory: the concrete gain-bearing items found in the draft but
  absent from the consensus, detected heuristically:
    NUMBERS  - prices, percentages, counts, years (the substance of a stat).
    QUOTES   - quoted operator/customer voice (straight or curly quotes).
    ENTITIES - multi-word proper nouns (crews, streets, neighborhoods, brands),
               the local-specifics surface where first-party gain lives.
- A verdict. With a consensus file, the draft FAILS (exit 1) when the residual
  falls under --min-gain (default 0.30): it is a rehash. Without a consensus
  file the tool cannot diff, so it only inventories the draft's specificity
  signals and exits 0 with a note that a baseline is required for a true score.

Law 8 / Law 15 posture: this measures the thing Google's patent rewards. It
never scores or games AI-detection, and coverage of expected terms is a floor,
never the reward. A low residual is a prompt to add real first-party facts, not
to pad word count.

Usage
-----
  python information_gain_scorer.py draft.md --consensus baseline.md
  python information_gain_scorer.py draft.md -c baseline.md --min-gain 0.35
  python information_gain_scorer.py draft.md          # inventory only, no diff
  cat draft.md | python information_gain_scorer.py - -c baseline.md
  python information_gain_scorer.py --self-test

Exit code: 0 = pass (or inventory-only), 1 = rehash / residual under threshold.
"""

import argparse
import difflib
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from readability_scorer import strip_markdown  # stdlib-only sibling helper

LDQUO = chr(0x201C)  # left double quotation mark
RDQUO = chr(0x201D)  # right double quotation mark

NUMBER_RE = re.compile(r"\$\s?\d[\d,]*(?:\.\d+)?%?|\b\d[\d,]*(?:\.\d+)?\s?%|\b(?:19|20)\d{2}\b|\b\d[\d,]*(?:\.\d+)?\b")
QUOTE_RE = re.compile(r'"([^"\n]{6,240})"' + r"|" + LDQUO + r"([^" + RDQUO + r"\n]{6,240})" + RDQUO)
ENTITY_RE = re.compile(r"\b[A-Z][a-zA-Z0-9]+(?:\s+(?:[A-Z][a-zA-Z0-9]+|[a-z]{1,3}\s+[A-Z][a-zA-Z0-9]+)){1,4}\b")

# Words that start a sentence and would be miscaptured as entities.
STOP_LEAD = {
    "The", "This", "That", "These", "Those", "Our", "Your", "We", "You",
    "When", "Where", "What", "Why", "How", "If", "In", "On", "At", "For",
    "And", "But", "Most", "Every", "Each", "A", "An", "It", "They", "He",
    "She", "Google", "Call", "Book", "Get", "See",
}


def content_tokens(text):
    return re.findall(r"[a-z0-9']+", strip_markdown(text).lower())


def extract_items(text):
    """Return {category: [item, ...]} of gain-bearing specifics in the draft."""
    clean = strip_markdown(text)
    numbers = [m.group(0).strip() for m in NUMBER_RE.finditer(clean)]

    quotes = []
    for m in QUOTE_RE.finditer(clean):
        q = m.group(1) or m.group(2) or ""
        q = q.strip()
        if q:
            quotes.append(q)

    entities = []
    for m in ENTITY_RE.finditer(clean):
        phrase = m.group(0).strip()
        first = phrase.split()[0]
        if first in STOP_LEAD:
            # Drop a leading sentence-initial stopword, keep the rest if it is
            # still a multi-word proper noun.
            rest = phrase.split(None, 1)
            if len(rest) == 2 and len(rest[1].split()) >= 2:
                entities.append(rest[1])
            continue
        entities.append(phrase)

    return {
        "NUMBERS": _dedupe(numbers),
        "QUOTES": _dedupe(quotes),
        "ENTITIES": _dedupe(entities),
    }


def _dedupe(seq):
    return list(dict.fromkeys(seq))


def net_new(items, consensus_text):
    """Items present in the draft but absent from the consensus baseline."""
    hay = consensus_text.lower()
    new = {}
    for cat, values in items.items():
        new[cat] = [v for v in values if v.lower() not in hay]
    return new


def residual_ratio(draft_text, consensus_text):
    """Proportion of the draft's token sequence NOT aligned to the consensus."""
    draft = content_tokens(draft_text)
    base = content_tokens(consensus_text)
    if not draft:
        return 0.0, 0, 0
    matcher = difflib.SequenceMatcher(None, base, draft, autojunk=False)
    matched = sum(block.size for block in matcher.get_matching_blocks())
    matched = min(matched, len(draft))
    return 1.0 - (matched / len(draft)), matched, len(draft)


def score(draft_text, consensus_text=None):
    items = extract_items(draft_text)
    result = {
        "items": items,
        "item_count": sum(len(v) for v in items.values()),
        "has_consensus": consensus_text is not None,
    }
    if consensus_text is None:
        result["net_new"] = items  # no baseline: everything is "unverified new"
        result["net_new_count"] = result["item_count"]
        result["residual"] = None
        return result
    ratio, matched, total = residual_ratio(draft_text, consensus_text)
    new = net_new(items, consensus_text)
    result["residual"] = ratio
    result["matched_tokens"] = matched
    result["total_tokens"] = total
    result["net_new"] = new
    result["net_new_count"] = sum(len(v) for v in new.values())
    return result


def read_source(path):
    if path == "-":
        return sys.stdin.read()
    with open(path, "r", encoding="utf-8") as fh:
        return fh.read()


def run(args):
    draft = read_source(args.path)
    src = "<stdin>" if args.path == "-" else args.path
    consensus = None
    if args.consensus:
        with open(args.consensus, "r", encoding="utf-8") as fh:
            consensus = fh.read()

    result = score(draft, consensus)

    print("Information-gain report for %s" % src)
    if not result["has_consensus"]:
        print("  no consensus baseline given: inventory only, no residual score")
        print("  specificity signals found in the draft:")
        _print_inventory(result["items"])
        print("")
        print("NOTE  pass a caller-generated consensus baseline with --consensus")
        print("      to score the true information-gain residual (Law 15).")
        return 0

    ratio = result["residual"]
    print("  residual (draft material absent from consensus): %.1f%%" % (100 * ratio))
    print("  aligned %d / %d draft tokens to the consensus"
          % (result["matched_tokens"], result["total_tokens"]))
    print("  net-new specific items: %d" % result["net_new_count"])
    print("")
    print("  net-new inventory (in the draft, absent from consensus):")
    _print_inventory(result["net_new"])
    print("")

    if ratio < args.min_gain:
        print("FAIL  residual %.1f%% < %.1f%% floor: this reads as a rehash of the"
              % (100 * ratio, 100 * args.min_gain))
        print("      consensus. Add real first-party facts (prices, project data,")
        print("      local specifics, operator quotes), do not pad word count.")
        return 1
    if result["net_new_count"] == 0:
        print("WARN  residual clears the floor but zero concrete net-new items were")
        print("      detected. Confirm the divergence is substance, not paraphrase.")
    print("PASS  residual %.1f%% >= %.1f%% floor (net-new value over the consensus)"
          % (100 * ratio, 100 * args.min_gain))
    return 0


def _print_inventory(inv):
    order = ["NUMBERS", "QUOTES", "ENTITIES"]
    for cat in order:
        vals = inv.get(cat, [])
        shown = vals[:12]
        extra = len(vals) - len(shown)
        listing = ", ".join(repr(v) for v in shown) if shown else "(none)"
        if extra > 0:
            listing += ", ... (+%d more)" % extra
        print("    %-9s %2d  %s" % (cat, len(vals), listing))


def self_test():
    consensus = (
        "Roof repair fixes damage to a roof. A roofer inspects the roof, finds "
        "the leak, and replaces the broken shingles or flashing. Most repairs "
        "can be done in a day. It is important to hire a licensed and insured "
        "roofer. Prices vary depending on the size and type of the damage. A "
        "good roofer will give you a written estimate before starting the work."
    )
    rehash = (
        "# Roof Repair\n\n"
        "Roof repair fixes damage to a roof. A roofer inspects the roof, finds "
        "the leak, and replaces the broken shingles or flashing. Most repairs "
        "can be done in a day. It is important to hire a licensed and insured "
        "roofer. Prices vary depending on the size and type of the damage."
    )
    rich = (
        "# Roof Repair in Round Rock\n\n"
        "Acme Roofing has patched hail damage across Round Rock and Williamson "
        "County since 2004. After the April 2023 storm on Gattis School Road we "
        "replaced 42 squares of shingle in a single day for $6,400, and the "
        'homeowner told us, "the crew was off the roof before the kids got home '
        'from school." Our permit with the City of Round Rock covers tear-off '
        "to 6:12 pitch, and we stock GAF Timberline HDZ on the truck so 8 of 10 "
        "repairs finish without a second visit."
    )

    r_rehash = score(rehash, consensus)
    r_rich = score(rich, consensus)

    assert r_rehash["residual"] < r_rich["residual"], (
        "rich draft must have a larger residual than the rehash: %.2f vs %.2f"
        % (r_rich["residual"], r_rehash["residual"]))
    assert r_rehash["residual"] < 0.30, (
        "rehash residual should be under the 0.30 floor, got %.2f"
        % r_rehash["residual"])
    assert r_rich["residual"] >= 0.30, (
        "rich residual should clear the 0.30 floor, got %.2f" % r_rich["residual"])
    assert r_rich["net_new_count"] > 0, "rich draft should have net-new items"
    new_numbers = r_rich["net_new"]["NUMBERS"]
    assert any("6,400" in n or "42" in n or "2023" in n for n in new_numbers), (
        "expected a net-new number, got %s" % new_numbers)
    assert r_rich["net_new"]["QUOTES"], "expected a net-new operator quote"
    assert any("Gattis" in e or "Round Rock" in e or "Acme" in e
               for e in r_rich["net_new"]["ENTITIES"]), (
        "expected a net-new local entity, got %s" % r_rich["net_new"]["ENTITIES"])

    # No-consensus path must exit clean and inventory the draft.
    r_none = score(rich, None)
    assert r_none["residual"] is None and r_none["item_count"] > 0

    print("self-test OK")
    print("  rehash residual: %.1f%% (rehash, would FAIL)"
          % (100 * r_rehash["residual"]))
    print("  rich   residual: %.1f%% with %d net-new items (would PASS)"
          % (100 * r_rich["residual"], r_rich["net_new_count"]))
    return 0


def build_parser():
    p = argparse.ArgumentParser(
        description="Score a draft's net-new value vs a caller-supplied consensus baseline (Law 15).",
    )
    p.add_argument("path", nargs="?", default="-",
                   help="path to the draft markdown/text, or '-' for stdin")
    p.add_argument("--consensus", "-c",
                   help="path to the caller-generated bland consensus baseline")
    p.add_argument("--min-gain", type=float, default=0.30,
                   help="residual floor below which the draft is a rehash (default 0.30)")
    p.add_argument("--self-test", action="store_true",
                   help="run the built-in self-test and exit")
    return p


def main(argv=None):
    args = build_parser().parse_args(argv)
    if args.self_test:
        return self_test()
    return run(args)


if __name__ == "__main__":
    sys.exit(main())
