"""Data access for the grid ledgers (``grid_definitions`` / ``grid_runs`` /
``grid_points``) via the RLS-scoped ``rls_connection`` seam + the privileged
``ServiceGridStore`` the worker writes through.

Mirrors ``app.modules.local_seo.repo`` exactly - same two seams, same scoping rules,
same synchronous psycopg methods offloaded by the router with ``asyncio.to_thread``.
Staff read the whole grid surface, clients are excluded (no base-table select policy),
and only leads may write (the 0138 insert/update policies + the router's
``require_role`` gate).

WHY POINTS ARE WRITTEN AS THEY ARE PROBED, not batched at the end. A grid run issues
up to 41 PAID provider calls over several minutes. Buffering the results in worker
memory means a crash, a redeploy or a reaped lease discards observations that were
already bought - and leaves a `running` row with nothing under it. Each probe is
therefore inserted as it completes, so the evidence table always reflects what has
actually been paid for, and a run that dies halfway still shows its measured points
with the remainder honestly counted as unmeasured (``service.summarize``).

SQL rules (impersonation-review mandate): every VALUE is a bound param (``%s``), never
string-formatted; table/column names are static literals.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastapi import Depends
from psycopg.types.json import Jsonb

from app.core.auth import CurrentUserDep
from app.db.database import privileged_connection, rls_connection

_Rows = list[dict[str, Any]]

# The definition read projection: the base row + the joined profile's location label
# (the board's `[Location]` cell) and the place id the probe matches against. An INNER
# join is correct - a definition cannot exist without its profile (NOT NULL FK).
_DEFINITION_SELECT = (
    "select d.*, p.location_label, p.place_id, p.nap_name "
    "from public.grid_definitions d "
    "join public.gbp_profiles p on p.id = d.profile_id"
)


class GridRepo:
    """Thin RLS-scoped repository over the grid definitions, runs and points."""

    def __init__(self, user_id: str) -> None:
        self._user_id = user_id

    # --- definitions ----------------------------------------------------------
    def list_definitions(
        self, *, client_id: str | None = None, limit: int = 50, offset: int = 0
    ) -> _Rows:
        with rls_connection(self._user_id) as cur:
            if client_id:
                cur.execute(
                    _DEFINITION_SELECT + " where d.client_id = %s "
                    "order by d.created_at desc limit %s offset %s",
                    (client_id, limit, offset),
                )
            else:
                cur.execute(
                    _DEFINITION_SELECT + " order by d.created_at desc limit %s offset %s",
                    (limit, offset),
                )
            return cur.fetchall()

    def get_definition(self, definition_id: str) -> dict[str, Any] | None:
        with rls_connection(self._user_id) as cur:
            cur.execute(_DEFINITION_SELECT + " where d.id = %s limit 1", (definition_id,))
            return cur.fetchone()

    def create_definition(
        self,
        *,
        client_id: str,
        client_name: str,
        profile_id: str,
        keyword: str,
        center_lat: float,
        center_lng: float,
        center_source: str,
        rings: int,
        ring_spacing_km: float,
        shape: str = "square",
        grid_size: int = 5,
        matched_name: str = "",
        matched_address: str = "",
    ) -> dict[str, Any] | None:
        """Insert one standing grid. ``point_count`` is GENERATED by 0138 and returned
        so the caller can show the operator the probe count it just committed to."""
        with rls_connection(self._user_id) as cur:
            cur.execute(
                "insert into public.grid_definitions "
                "(client_id, client_name, profile_id, keyword, center_lat, center_lng, "
                " center_source, rings, ring_spacing_km, shape, grid_size, "
                " center_matched_name, center_matched_address) "
                "values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) "
                "returning *",
                (client_id, client_name, profile_id, keyword, center_lat, center_lng,
                 center_source, rings, ring_spacing_km, shape, grid_size,
                 matched_name[:200], matched_address[:300]),
            )
            return cur.fetchone()

    def set_active(self, definition_id: str, *, is_active: bool) -> dict[str, Any] | None:
        with rls_connection(self._user_id) as cur:
            cur.execute(
                "update public.grid_definitions set is_active = %s where id = %s returning *",
                (is_active, definition_id),
            )
            return cur.fetchone()

    def profile(self, profile_id: str) -> dict[str, Any] | None:
        """The GBP profile a grid centres on - the existing 0039 location ledger. This
        module reads it and never forks it."""
        with rls_connection(self._user_id) as cur:
            cur.execute(
                "select id, client_id, client_name, location_label, place_id, nap_name, "
                "       nap_address "
                "from public.gbp_profiles where id = %s limit 1",
                (profile_id,),
            )
            return cur.fetchone()

    def business_profile(self, client_id: str) -> dict[str, Any] | None:
        """This client's canonical business identity - the NAP the whole platform
        already agrees on (`business_profiles`, the citations module's locked NAP;
        falling back to the onboarding-era `client_business_profiles`).

        WHY THE GRID READS THIS RATHER THAN ASKING. An operator selecting a client has
        already told the platform which business this is; making them then type its
        name, address and location label is asking for facts the system holds - and
        every retype is a chance to enter a different address than the one the
        citations module is submitting, which is the NAP inconsistency the off-page
        module exists to eliminate.
        """
        with rls_connection(self._user_id) as cur:
            cur.execute(
                "select business_name, address_line1, address_line2, city, region, "
                "       postal_code, phone, website_url "
                "from public.business_profiles where client_id = %s "
                "order by is_primary desc, created_at asc limit 1",
                (client_id,),
            )
            row = cur.fetchone()
            if row:
                return row
            # The onboarding-era table, for a client profiled before `business_profiles`.
            cur.execute(
                "select business_name, address_line1, address_line2, city, region, "
                "       postal_code, phone, website_url "
                "from public.client_business_profiles where client_id = %s limit 1",
                (client_id,),
            )
            return cur.fetchone()

    def profile_for_client(self, client_id: str, *, label: str) -> dict[str, Any] | None:
        """This client's GBP location row for ``label``, if it already exists."""
        with rls_connection(self._user_id) as cur:
            cur.execute(
                "select id, client_id, client_name, location_label, place_id, nap_name, "
                "       nap_address "
                "from public.gbp_profiles where client_id = %s and location_label = %s "
                "limit 1",
                (client_id, label),
            )
            return cur.fetchone()

    def create_profile(
        self,
        *,
        client_id: str,
        client_name: str,
        label: str,
        nap_name: str,
        nap_address: str,
        nap_phone: str,
        place_id: str,
        website: str,
    ) -> dict[str, Any] | None:
        """Create the `0039` location row this grid will centre on.

        The grid module still does NOT own locations - it writes the location ledger
        `0039` defines, through the same columns `local_seo` uses, so one location is
        one row whichever surface created it.
        """
        with rls_connection(self._user_id) as cur:
            cur.execute(
                "insert into public.gbp_profiles "
                "(client_id, client_name, location_label, nap_name, nap_address, "
                " nap_phone, place_id, website_uri) "
                "values (%s, %s, %s, %s, %s, %s, %s, %s) "
                "returning id, client_id, client_name, location_label, place_id, "
                "          nap_name, nap_address",
                (client_id, client_name, label, nap_name[:200], nap_address[:300],
                 nap_phone[:60], place_id[:200], website[:300]),
            )
            return cur.fetchone()

    def client_name(self, client_id: str) -> str | None:
        """The display snapshot, so the internal client_id never surfaces."""
        with rls_connection(self._user_id) as cur:
            cur.execute("select name from public.clients where id = %s limit 1", (client_id,))
            row = cur.fetchone()
            return str(row["name"]) if row else None

    # --- runs + points --------------------------------------------------------
    def list_runs(self, definition_id: str, *, limit: int = 30, offset: int = 0) -> _Rows:
        with rls_connection(self._user_id) as cur:
            cur.execute(
                "select * from public.grid_runs where definition_id = %s "
                "order by created_at desc limit %s offset %s",
                (definition_id, limit, offset),
            )
            return cur.fetchall()

    def get_run(self, run_id: str) -> dict[str, Any] | None:
        with rls_connection(self._user_id) as cur:
            cur.execute("select * from public.grid_runs where id = %s limit 1", (run_id,))
            return cur.fetchone()

    def latest_run(self, definition_id: str) -> dict[str, Any] | None:
        with rls_connection(self._user_id) as cur:
            cur.execute(
                "select * from public.grid_runs where definition_id = %s "
                "order by created_at desc limit 1",
                (definition_id,),
            )
            return cur.fetchone()

    def points(self, run_id: str) -> _Rows:
        """Every probe of one run - the heat map. Ordered by ring then label so the
        centre leads and each ring reads clockwise, which is the order a legend and a
        keyboard-navigable table both want."""
        with rls_connection(self._user_id) as cur:
            cur.execute(
                "select * from public.grid_points where run_id = %s order by ring, label",
                (run_id,),
            )
            return cur.fetchall()

    def has_open_run(self, definition_id: str) -> bool:
        """Whether a run for this grid is already queued or running.

        The router refuses a second manual run while one is in flight: each run is up
        to 41 paid probes, so a double-click must not become a double bill. The job
        contract's idempotency key is the durable guard; this is the cheap one that
        lets the API answer 409 instead of silently collapsing.
        """
        with rls_connection(self._user_id) as cur:
            cur.execute(
                "select 1 from public.grid_runs "
                "where definition_id = %s and status in ('queued', 'running') limit 1",
                (definition_id,),
            )
            return cur.fetchone() is not None


def get_grid_repo(user: CurrentUserDep) -> GridRepo:
    """Dependency: a repo bound to the caller's verified user id (RLS-scoped)."""
    return GridRepo(user.id)


GridRepoDep = Annotated[GridRepo, Depends(get_grid_repo)]


# --------------------------------------------------------------------------- #
# Privileged (service_role, BYPASSRLS) store for the WORKER.
# --------------------------------------------------------------------------- #
class ServiceGridStore:
    """Concrete grid store over ``privileged_connection`` (BYPASSRLS).

    Stateless: each method opens its own connection, exactly like
    ``ServiceLocalStore``.
    """

    def claim_due_definitions(self, limit: int) -> _Rows:
        """Atomically claim up to ``limit`` ACTIVE grids to run.

        ``FOR UPDATE SKIP LOCKED`` with ``last_run_at`` stamped AT CLAIM, mirroring
        ``ServiceLocalStore.claim_due_rankings``: the stamp rotates the queue so a
        grid that fails repeatedly cannot starve every grid behind it. It records
        "we looked at this", not "this succeeded" - the run row records that.
        """
        with privileged_connection() as cur:
            cur.execute(
                "with due as ( "
                "  select id from public.grid_definitions "
                "  where is_active "
                "  order by last_run_at asc nulls first "
                "  for update skip locked "
                "  limit %s "
                ") "
                "update public.grid_definitions d set last_run_at = now() "
                "from due where d.id = due.id "
                "returning d.id",
                (limit,),
            )
            return cur.fetchall()

    def definition(self, definition_id: str) -> dict[str, Any] | None:
        """One grid plus the profile facts the probe needs to recognise the client's
        own listing in the pack."""
        with privileged_connection() as cur:
            cur.execute(
                "select d.*, p.place_id, p.nap_name, p.location_label "
                "from public.grid_definitions d "
                "join public.gbp_profiles p on p.id = d.profile_id "
                "where d.id = %s limit 1",
                (definition_id,),
            )
            return cur.fetchone()

    def open_run(self, definition_id: str, *, job_run_id: str | None = None) -> str | None:
        """Create the `running` row, copying the geometry AS RUN.

        The geometry is copied rather than referenced so a definition edited next week
        cannot retroactively change what this run's points meant.
        """
        with privileged_connection() as cur:
            cur.execute(
                "insert into public.grid_runs "
                "(definition_id, client_id, status, center_lat, center_lng, rings, "
                " ring_spacing_km, shape, grid_size, points_total, job_run_id, started_at) "
                "select d.id, d.client_id, 'running', d.center_lat, d.center_lng, "
                "       d.rings, d.ring_spacing_km, d.shape, d.grid_size, "
                "       d.point_count, %s, now() "
                "from public.grid_definitions d where d.id = %s "
                "returning id",
                (job_run_id, definition_id),
            )
            row = cur.fetchone()
            return str(row["id"]) if row else None

    def record_point(
        self,
        run_id: str,
        *,
        client_id: str,
        lat: float,
        lng: float,
        label: str,
        ring: int,
        status: str,
        rank: int | None,
        top_competitors: list[str],
        found_url: str,
        error: str,
    ) -> None:
        """Append ONE probe. Written as it completes - see the module docstring.

        The three-state contract is enforced by 0138's CHECK constraints, not by this
        method: a caller that tried to write ``status='error'`` with a rank, or
        ``'absent'`` with one, is refused by Postgres. That is deliberate - the
        guarantee has to survive a caller that is wrong.
        """
        with privileged_connection() as cur:
            cur.execute(
                "insert into public.grid_points "
                "(run_id, client_id, lat, lng, label, ring, status, rank, "
                " top_competitors, found_url, error) "
                "values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) "
                "on conflict (run_id, label) do nothing",
                (run_id, client_id, lat, lng, label, ring, status, rank,
                 Jsonb(top_competitors), found_url, error),
            )

    def finalize_run(
        self,
        run_id: str,
        *,
        status: str,
        reason: str,
        points_ranked: int,
        points_absent: int,
        points_error: int,
        avg_rank: float | None,
        share_top3: float | None,
        provider: str,
        cost_usd: float,
    ) -> None:
        """Stamp the derived counters and the terminal state in one statement."""
        with privileged_connection() as cur:
            cur.execute(
                "update public.grid_runs set "
                "  status = %s, reason = %s, points_ranked = %s, points_absent = %s, "
                "  points_error = %s, avg_rank = %s, share_top3 = %s, provider = %s, "
                "  cost_usd = %s, finished_at = now() "
                "where id = %s",
                (status, reason, points_ranked, points_absent, points_error, avg_rank,
                 share_top3, provider, cost_usd, run_id),
            )

    def close_run_without_probing(self, run_id: str, *, status: str, reason: str) -> None:
        """Terminate a run that never issued a probe (blocked / cancelled).

        ``reason`` is REQUIRED by ``grid_runs_reason_required_ck`` for these states, so
        a blocked run always says why it was blocked.
        """
        with privileged_connection() as cur:
            cur.execute(
                "update public.grid_runs set status = %s, reason = %s, finished_at = now() "
                "where id = %s",
                (status, reason, run_id),
            )

    def open_run_ids(self, definition_id: str) -> list[str]:
        """Runs still `queued`/`running` for this grid - used to adopt an orphan rather
        than open a second row when a redelivery finds one already in flight."""
        with privileged_connection() as cur:
            cur.execute(
                "select id from public.grid_runs "
                "where definition_id = %s and status in ('queued', 'running') "
                "order by created_at asc",
                (definition_id,),
            )
            return [str(r["id"]) for r in cur.fetchall()]


def service_grid_store() -> ServiceGridStore:
    """Factory so the worker can be unit-tested against an in-memory fake."""
    return ServiceGridStore()


__all__ = [
    "GridRepo",
    "GridRepoDep",
    "ServiceGridStore",
    "get_grid_repo",
    "service_grid_store",
]
